"use client";

import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, Check, Clock3, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

export function LiveStudentSchedule({ onStart }: { onStart: (jadwalId: string) => void }) {
  const [student, setStudent] = useState<any>(null); const [schedules, setSchedules] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/siswa/jadwal", { cache: "no-store" }).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setStudent(result.student); setSchedules(result.schedules || []); }).catch(error => setError(error.message || "Jadwal gagal dimuat.")).finally(() => setLoading(false)); }, []);
  return <div className="space-y-7"><div className="rounded-2xl bg-[#24294a] p-6 text-white sm:p-8"><div className="max-w-xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#aaaed0]">Ringkasan ujianmu</p><h2 className="mt-3 text-2xl font-extrabold tracking-tight sm:text-3xl">Siapkan dirimu untuk ujian berikutnya.</h2><p className="mt-3 text-sm leading-6 text-[#bdc1d9]">Baca petunjuk dengan teliti dan pastikan koneksi internetmu stabil sebelum memulai.</p><div className="mt-6 flex flex-wrap gap-6 text-xs text-[#c5c8dd]"><span className="flex items-center gap-2"><BookOpen size={15} className="text-[#a19dff]" /> {schedules.length} jadwal tersedia</span><span className="flex items-center gap-2"><Clock3 size={15} className="text-[#a19dff]" /> Terhubung ke sistem</span></div></div></div><div><div className="mb-4 flex items-end justify-between"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.15em] text-brand">Jadwal tersedia</p><h2 className="text-xl font-extrabold text-ink">{student?.kelas?.nama_kelas || "Ujian kamu"}</h2></div><Badge tone="brand">{student?.kelas?.nama_kelas || "Siswa"}</Badge></div>{error && <div className="mb-4 rounded-xl bg-danger-soft px-4 py-3 text-xs font-semibold text-danger">{error}</div>}{loading ? <Card><CardContent className="p-8 text-center text-sm text-muted">Memuat jadwal dari Supabase...</CardContent></Card> : schedules.length === 0 ? <Card><CardContent className="p-8 text-center text-sm text-muted">Belum ada jadwal ujian aktif untuk kelasmu.</CardContent></Card> : <div className="grid gap-4 lg:grid-cols-2">{schedules.map(schedule => <ExamCard key={schedule.id} schedule={schedule} onStart={onStart} />)}</div>}</div><Card className="border-[#dcd9ff] bg-[#fbfbff]"><CardContent className="flex gap-3 p-5"><ShieldCheck size={18} className="mt-0.5 shrink-0 text-brand" /><div><p className="text-sm font-bold text-ink">Tips sebelum memulai</p><ul className="mt-2 space-y-1 text-xs leading-5 text-muted"><li>• Pastikan kamu berada di tempat yang tenang.</li><li>• Jawaban tersimpan otomatis setiap kali ada perubahan.</li><li>• Jangan menutup tab atau berpindah aplikasi selama ujian.</li></ul></div></CardContent></Card></div>;
}

function ExamCard({ schedule, onStart }: { schedule: any; onStart: (id: string) => void }) { const mapel = schedule.bank_soal?.mapel?.nama_mapel || schedule.bank_soal?.nama_bank_soal || "Ujian"; const date = new Date(schedule.waktu_mulai); const end = schedule.waktu_selesai ? new Date(schedule.waktu_selesai) : null; const active = schedule.status === "berlangsung" || (date.getTime() <= Date.now() + 60 * 60 * 1000 && schedule.status === "siap"); return <Card className={cn("overflow-hidden", active && "border-brand/30")}><div className={cn("h-1.5", active ? "bg-brand" : "bg-[#e0e3e9]")} /><CardContent className="p-5"><div className="flex items-start justify-between"><div className={cn("grid h-11 w-11 place-items-center rounded-xl text-xs font-extrabold", active ? "bg-brand-soft text-brand" : "bg-canvas text-muted")}>{mapel.slice(0, 3).toUpperCase()}</div><Badge tone={active ? "brand" : "neutral"}>{schedule.status}</Badge></div><h3 className="mt-5 text-lg font-bold text-ink">{mapel}</h3><p className="mt-1 text-xs text-muted">Bank soal {schedule.bank_soal?.nama_bank_soal || "-"} · {schedule.kelas?.nama_kelas || "-"}</p><div className="mt-5 grid grid-cols-2 gap-y-3 border-y border-line py-4"><div><p className="text-[10px] uppercase tracking-wider text-muted">Waktu</p><p className="mt-1 text-xs font-bold text-ink">{date.toLocaleDateString("id-ID")}</p><p className="mt-0.5 text-xs text-muted">{date.toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })}{end ? ` – ${end.toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })}` : ""}</p></div><div><p className="text-[10px] uppercase tracking-wider text-muted">Durasi</p><p className="mt-1 text-xs font-bold text-ink">{schedule.durasi_menit} menit</p><p className="mt-0.5 text-xs text-muted">Essay</p></div></div><Button onClick={() => onStart(schedule.id)} disabled={!active} variant={active ? "default" : "secondary"} className="mt-5 w-full">{active ? "Mulai ujian" : "Belum dibuka"}{active && <ArrowRight size={15} />}</Button></CardContent></Card>; }

export function LiveResults() { const [data, setData] = useState<any[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { fetch("/api/siswa/hasil", { cache: "no-store" }).then(r => r.json()).then(result => setData(result.data || [])).finally(() => setLoading(false)); }, []); return <div className="space-y-7"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.15em] text-brand">Riwayat</p><h2 className="text-2xl font-extrabold tracking-tight text-ink">Hasil pengerjaan</h2><p className="mt-1 text-sm text-muted">Lihat status pengerjaan ujianmu.</p></div><Card><CardHeader><CardTitle>Daftar ujian</CardTitle></CardHeader><CardContent className="space-y-3">{loading ? <p className="p-4 text-sm text-muted">Memuat hasil...</p> : data.length === 0 ? <p className="p-4 text-sm text-muted">Belum ada riwayat ujian.</p> : data.map(item => <div key={item.id} className="flex flex-col gap-3 rounded-xl border border-line p-4 sm:flex-row sm:items-center"><div className={cn("grid h-10 w-10 shrink-0 place-items-center rounded-xl text-xs font-extrabold", item.status === "selesai" ? "bg-success-soft text-success" : "bg-canvas text-muted")}><BookOpen size={16} /></div><div className="flex-1"><p className="text-sm font-bold text-ink">{item.jadwal?.bank_soal?.mapel?.nama_mapel || item.jadwal?.bank_soal?.nama_bank_soal || "Ujian"}</p><p className="mt-1 text-xs text-muted">Attempt ke-{item.attempt_ke} · {item.status}</p></div><Badge tone={item.status === "selesai" ? "success" : item.status === "terputus" ? "danger" : "neutral"}>{item.status === "selesai" && <Check size={12} className="mr-1" />}{item.status}</Badge></div>)}</CardContent></Card><div className="flex gap-3 rounded-xl border border-[#dcd9ff] bg-[#fbfbff] p-4 text-xs leading-5 text-muted"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-brand" /><span>Nilai essay dinilai manual oleh guru di luar aplikasi. Halaman ini hanya menampilkan status pengerjaan.</span></div></div>; }
