"use client";

import { useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { Activity, AlertTriangle, ArrowDownToLine, ArrowUpFromLine, Bell, BookOpen, CalendarDays, Check, ChevronDown, ChevronRight, CircleHelp, FileSpreadsheet, Filter, GraduationCap, LayoutDashboard, Menu, MoreHorizontal, Plus, RefreshCw, Search, Settings, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cn } from "@/lib/utils";

type Section = "dashboard" | "jadwal" | "siswa" | "bank-soal" | "kelas" | "mapel";
type Status = "sedang mengerjakan" | "belum mulai" | "selesai" | "terputus";

const nav = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { id: "jadwal", label: "Jadwal Ujian", icon: CalendarDays, count: "3" },
  { id: "siswa", label: "Manajemen Siswa", icon: Users },
  { id: "bank-soal", label: "Bank Soal", icon: BookOpen },
  { id: "kelas", label: "Kelas", icon: GraduationCap },
  { id: "mapel", label: "Mata Pelajaran", icon: FileSpreadsheet },
] as const;

const schedules = [
  { subject: "Matematika", code: "MTK10", className: "X TKJ 1", date: "24 Sep 2024", time: "08:00 – 10:00", status: "berlangsung", students: "28/32", color: "#e9e8ff", text: "#5048c8" },
  { subject: "Bahasa Indonesia", code: "BIND10", className: "X TKJ 2", date: "25 Sep 2024", time: "09:00 – 11:00", status: "siap", students: "0/30", color: "#e5f7f0", text: "#198c69" },
  { subject: "Pemrograman Dasar", code: "PD10", className: "X RPL 1", date: "27 Sep 2024", time: "07:30 – 09:30", status: "draft", students: "0/28", color: "#fff2dc", text: "#b77300" },
];
const students = [
  { name: "Ahmad Fauzan", no: "u01810001", className: "X TKJ 1", status: "sedang mengerjakan" as Status, last: "Aktif 2 menit lalu" },
  { name: "Dinda Maharani", no: "u01810002", className: "X TKJ 1", status: "selesai" as Status, last: "Selesai 08:53" },
  { name: "Rizky Pratama", no: "u01810003", className: "X TKJ 1", status: "terputus" as Status, last: "Pelanggaran tab" },
  { name: "Siti Aisyah", no: "u01810004", className: "X TKJ 1", status: "belum mulai" as Status, last: "-" },
];

function StatusBadge({ status }: { status: string }) {
  const tone: "neutral" | "success" | "warning" | "danger" | "brand" = status === "berlangsung" || status === "sedang mengerjakan" ? "brand" : status === "siap" || status === "selesai" ? "success" : status === "terputus" ? "danger" : status === "draft" ? "warning" : "neutral";
  return <Badge tone={tone}>{status}</Badge>;
}

function Logo() { return <div className="flex items-center gap-2.5 text-[17px] font-extrabold tracking-tight text-ink"><div className="grid h-8 w-8 place-items-center rounded-[10px] bg-brand text-white"><Sparkles size={16} /></div>EssaySpace</div>; }

export default function AdminPage() {
  const params = useParams<{ section?: string[] }>();
  const section = ((params?.section?.[0] || "dashboard") as Section);
  const active: Section = nav.some(item => item.id === section) ? section : "dashboard";
  const [mobileOpen, setMobileOpen] = useState(false);

  return <div className="min-h-screen bg-canvas">
    <aside className={cn("fixed inset-y-0 left-0 z-30 flex w-[248px] flex-col border-r border-line bg-white px-4 py-6 transition-transform lg:translate-x-0", mobileOpen ? "translate-x-0" : "-translate-x-full")}>
      <div className="px-2"><Logo /></div>
      <div className="mt-11 px-2 text-[10px] font-extrabold uppercase tracking-[.18em] text-[#adb4c2]">Menu utama</div>
      <nav className="mt-3 space-y-1">
        {nav.map(item => { const Icon = item.icon; return <Link key={item.id} href={`/admin/${item.id}`} onClick={() => setMobileOpen(false)} className={cn("flex h-10 items-center gap-3 rounded-lg px-3 text-sm font-semibold transition", active === item.id ? "bg-brand-soft text-brand" : "text-muted hover:bg-canvas hover:text-ink")}><Icon size={17} strokeWidth={active === item.id ? 2.5 : 2} /><span className="flex-1">{item.label}</span>{"count" in item && item.count && <span className="rounded bg-brand px-1.5 py-0.5 text-[10px] font-bold text-white">{item.count}</span>}</Link> })}
      </nav>
      <div className="mt-auto space-y-1">
        <Link href="/admin/pengaturan" className="flex h-10 items-center gap-3 rounded-lg px-3 text-sm font-semibold text-muted hover:bg-canvas hover:text-ink"><Settings size={17} /> Pengaturan</Link>
        <div className="mt-5 flex items-center gap-3 border-t border-line px-2 pt-5"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#ffe6ca] text-xs font-bold text-[#a96410]">AR</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-ink">Admin Rizky</p><p className="text-[11px] text-muted">Administrator</p></div><ChevronDown size={14} className="text-muted" /></div>
      </div>
    </aside>
    {mobileOpen && <button aria-label="Tutup menu" onClick={() => setMobileOpen(false)} className="fixed inset-0 z-20 bg-ink/30 lg:hidden" />}
    <div className="lg:pl-[248px]">
      <header className="sticky top-0 z-10 flex h-[72px] items-center justify-between border-b border-line bg-white/90 px-5 backdrop-blur-md sm:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobileOpen(true)} className="text-muted lg:hidden"><Menu size={21} /></button><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-muted">Selasa, 24 September 2024</p><h1 className="mt-0.5 text-lg font-bold text-ink">{active === "dashboard" ? "Selamat pagi, Rizky" : nav.find(n => n.id === active)?.label}</h1></div></div><div className="flex items-center gap-2"><button className="relative grid h-9 w-9 place-items-center rounded-lg text-muted hover:bg-canvas"><Bell size={18} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-danger" /></button><div className="mx-1 h-5 w-px bg-line" /><button className="hidden items-center gap-2 rounded-lg px-2 py-1.5 text-left hover:bg-canvas sm:flex"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#ffe6ca] text-[10px] font-bold text-[#a96410]">AR</div><ChevronDown size={14} className="text-muted" /></button></div></header>
      <main className="mx-auto max-w-[1400px] p-5 sm:p-8">{active === "dashboard" ? <Dashboard /> : <ManagementPage section={active} />}</main>
    </div>
  </div>;
}

function Dashboard() {
  const [monitorOpen, setMonitorOpen] = useState(false);
  const stats = [{ label: "Total Siswa", value: "248", meta: "+12 bulan ini", icon: Users, color: "brand" }, { label: "Bank Soal", value: "18", meta: "+3 bulan ini", icon: BookOpen, color: "success" }, { label: "Jadwal Aktif", value: "3", meta: "1 sedang berlangsung", icon: CalendarDays, color: "warning" }, { label: "Perlu Ditinjau", value: "7", meta: "Sesi terputus", icon: AlertTriangle, color: "danger" }];
  return <div className="space-y-7">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(s => { const Icon = s.icon; return <Card key={s.label} className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-muted">{s.label}</p><p className="mt-3 text-3xl font-extrabold tracking-tight text-ink">{s.value}</p></div><div className={cn("grid h-10 w-10 place-items-center rounded-xl", s.color === "brand" ? "bg-brand-soft text-brand" : s.color === "success" ? "bg-success-soft text-success" : s.color === "warning" ? "bg-warning-soft text-warning" : "bg-danger-soft text-danger")}><Icon size={19} /></div></div><p className={cn("mt-4 text-[11px] font-bold", s.color === "danger" ? "text-danger" : "text-muted")}>{s.meta}</p></Card> })}</div>
    <div className="grid gap-5 xl:grid-cols-[1.6fr_1fr]">
      <Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Jadwal ujian aktif</CardTitle><p className="mt-1 text-xs text-muted">Pantau progres ujian yang sedang berjalan</p></div><Link href="/admin/jadwal" className="flex items-center gap-1 text-xs font-bold text-brand">Lihat semua <ChevronRight size={14} /></Link></CardHeader><CardContent className="space-y-3">{schedules.map((s, i) => <div key={s.code} className="flex items-center gap-3 rounded-xl border border-line p-3.5 transition hover:border-[#ceccff] hover:bg-[#fcfcff]"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-xs font-extrabold" style={{ background: s.color, color: s.text }}>{s.code.slice(0, 3)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold text-ink">{s.subject}</p><StatusBadge status={s.status} /></div><p className="mt-1 text-xs text-muted">{s.className} <span className="mx-1 text-[#c4c8d2]">·</span> {s.date} · {s.time}</p></div><div className="hidden text-right sm:block"><p className="text-sm font-bold text-ink">{s.students}</p><p className="mt-1 text-[10px] text-muted">peserta</p></div>{i === 0 ? <button onClick={() => setMonitorOpen(true)} className="grid h-8 w-8 place-items-center rounded-lg text-muted hover:bg-brand-soft hover:text-brand"><Activity size={16} /></button> : <button className="grid h-8 w-8 place-items-center rounded-lg text-muted hover:bg-canvas"><MoreHorizontal size={17} /></button>}</div>)}</CardContent></Card>
      <Card><CardHeader><div className="flex items-start justify-between"><div><CardTitle>Aktivitas terbaru</CardTitle><p className="mt-1 text-xs text-muted">Update dari sistem</p></div><button className="text-muted"><MoreHorizontal size={18} /></button></div></CardHeader><CardContent><div className="relative space-y-6 pl-2 before:absolute before:left-[7px] before:top-2 before:h-[calc(100%-18px)] before:w-px before:bg-line">{[{ icon: Check, tone: "success", title: "Dinda Maharani menyelesaikan ujian", time: "8 menit lalu" }, { icon: AlertTriangle, tone: "danger", title: "Sesi Rizky Pratama terputus", time: "12 menit lalu" }, { icon: Plus, tone: "brand", title: "Bank soal MTK10 diperbarui", time: "1 jam lalu" }, { icon: Users, tone: "warning", title: "12 siswa baru diimpor", time: "Kemarin" }].map((a, i) => { const Icon = a.icon; return <div key={i} className="relative flex gap-3"><div className={cn("z-[1] grid h-4 w-4 shrink-0 place-items-center rounded-full ring-4 ring-white", a.tone === "success" ? "bg-success text-white" : a.tone === "danger" ? "bg-danger text-white" : a.tone === "brand" ? "bg-brand text-white" : "bg-warning text-white")}><Icon size={9} strokeWidth={3} /></div><div className="-mt-0.5"><p className="text-xs font-semibold leading-5 text-ink">{a.title}</p><p className="mt-0.5 text-[10px] text-muted">{a.time}</p></div></div> })}</div></CardContent></Card>
    </div>
    <Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Monitoring ujian — Matematika X TKJ 1</CardTitle><p className="mt-1 flex items-center gap-1.5 text-xs text-muted"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-success" /> Live update · terakhir diperbarui beberapa detik lalu</p></div><Button variant="secondary" size="sm" onClick={() => setMonitorOpen(true)}><Activity size={14} /> Buka monitoring</Button></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[{ n: "12", label: "Mengerjakan", tone: "brand" }, { n: "8", label: "Belum mulai", tone: "neutral" }, { n: "10", label: "Selesai", tone: "success" }, { n: "2", label: "Terputus", tone: "danger" }].map(x => <div key={x.label} className="rounded-xl bg-canvas p-4"><div className="flex items-center gap-2"><span className={cn("h-2 w-2 rounded-full", x.tone === "brand" ? "bg-brand" : x.tone === "success" ? "bg-success" : x.tone === "danger" ? "bg-danger" : "bg-[#aeb5c2]")} /><span className="text-xs font-semibold text-muted">{x.label}</span></div><p className="mt-2 text-xl font-extrabold text-ink">{x.n}</p></div>)}</div></CardContent></Card>
    {monitorOpen && <MonitorModal onClose={() => setMonitorOpen(false)} />}
  </div>;
}

function MonitorModal({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-line p-5"><div><div className="flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-success" /><h2 className="text-lg font-bold text-ink">Monitoring sesi ujian</h2></div><p className="mt-1 text-xs text-muted">Matematika · X TKJ 1 · 24 Sep 2024, 08:00–10:00</p></div><button onClick={onClose} className="text-muted hover:text-ink"><X size={19} /></button></div><div className="grid grid-cols-2 gap-3 p-5 sm:grid-cols-4">{[{n:"12",l:"Mengerjakan",c:"text-brand"},{n:"8",l:"Belum mulai",c:"text-muted"},{n:"10",l:"Selesai",c:"text-success"},{n:"2",l:"Terputus",c:"text-danger"}].map(x => <div key={x.l} className="rounded-xl border border-line p-3"><p className={cn("text-xl font-extrabold", x.c)}>{x.n}</p><p className="mt-1 text-[11px] text-muted">{x.l}</p></div>)}</div><div className="px-5 pb-5"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-bold text-ink">Daftar peserta <span className="font-normal text-muted">· 32 siswa</span></p><div className="flex gap-2"><button className="grid h-8 w-8 place-items-center rounded-lg border border-line text-muted"><Filter size={14} /></button><button className="grid h-8 w-8 place-items-center rounded-lg border border-line text-muted"><RefreshCw size={14} /></button></div></div><div className="overflow-hidden rounded-xl border border-line"><table className="w-full text-left text-xs"><thead className="bg-canvas text-[10px] uppercase tracking-wider text-muted"><tr><th className="px-4 py-3">Siswa</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Aktivitas</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-line">{students.map(s => <tr key={s.no}><td className="px-4 py-3"><p className="font-bold text-ink">{s.name}</p><p className="mt-0.5 text-[10px] text-muted">{s.no}</p></td><td className="px-4 py-3"><StatusBadge status={s.status} /></td><td className="px-4 py-3 text-muted">{s.last}</td><td className="px-4 py-3 text-right">{s.status === "terputus" && <Button variant="soft" size="sm">Tinjau</Button>}</td></tr>)}</tbody></table></div></div></div></div>; }

function ManagementPage({ section }: { section: Section }) {
  const [query, setQuery] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [showImport, setShowImport] = useState(false);
  const [toast, setToast] = useState("");
  const title = nav.find(n => n.id === section)?.label || "Manajemen";
  const description = { dashboard: "Kelola aktivitas ujian sekolah.", jadwal: "Atur waktu dan peserta ujian essay.", siswa: "Kelola akun dan akses peserta ujian.", "bank-soal": "Susun dan kelola bank soal essay.", kelas: "Kelola rombongan belajar sekolah.", mapel: "Kelola mata pelajaran dan kode bank soal." }[section] || "Kelola data operasional aplikasi.";
  const rows = section === "siswa" ? students.map((s, i) => ({ primary: s.name, secondary: s.no, extra: s.className, badge: s.status, meta: s.last, initials: s.name.split(" ").map(x => x[0]).join("") })) : section === "jadwal" ? schedules.map(s => ({ primary: s.subject, secondary: s.code, extra: s.className, badge: s.status, meta: `${s.date} · ${s.time}`, initials: s.code.slice(0, 2) })) : section === "bank-soal" ? [{ primary: "Matematika Dasar", secondary: "MTK10", extra: "Matematika", badge: "24 soal", meta: "Diperbarui 2 hari lalu", initials: "MT" }, { primary: "Bahasa Indonesia", secondary: "BIND10", extra: "Bahasa Indonesia", badge: "18 soal", meta: "Diperbarui 5 hari lalu", initials: "BI" }, { primary: "Pemrograman Dasar", secondary: "PD10", extra: "Produktif", badge: "32 soal", meta: "Diperbarui 1 minggu lalu", initials: "PD" }] : section === "kelas" ? [{ primary: "X TKJ 1", secondary: "TKJ-01", extra: "Teknik Komputer & Jaringan", badge: "32 siswa", meta: "Wali kelas: Pak Dimas", initials: "T1" }, { primary: "X TKJ 2", secondary: "TKJ-02", extra: "Teknik Komputer & Jaringan", badge: "30 siswa", meta: "Wali kelas: Bu Rina", initials: "T2" }, { primary: "X RPL 1", secondary: "RPL-01", extra: "Rekayasa Perangkat Lunak", badge: "28 siswa", meta: "Wali kelas: Pak Arif", initials: "R1" }] : [{ primary: "Matematika", secondary: "MTK", extra: "3 bank soal", badge: "Aktif", meta: "Terakhir diubah hari ini", initials: "M" }, { primary: "Bahasa Indonesia", secondary: "BIND", extra: "2 bank soal", badge: "Aktif", meta: "Terakhir diubah 3 hari lalu", initials: "BI" }, { primary: "Pemrograman Dasar", secondary: "PD", extra: "1 bank soal", badge: "Aktif", meta: "Terakhir diubah 1 minggu lalu", initials: "P" }];
  const filtered = rows.filter(r => `${r.primary} ${r.secondary} ${r.extra}`.toLowerCase().includes(query.toLowerCase()));
  function notify(message: string) { setToast(message); setTimeout(() => setToast(""), 2800); }
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.15em] text-brand">Data sekolah</p><h2 className="text-2xl font-extrabold tracking-tight text-ink">{title}</h2><p className="mt-1 text-sm text-muted">{description}</p></div><div className="flex gap-2"><Button variant="secondary" onClick={() => setShowImport(true)}><ArrowUpFromLine size={15} /> <span className="hidden sm:inline">Impor Excel</span></Button><Button onClick={() => setShowForm(true)}><Plus size={16} /> Tambah {section === "siswa" ? "siswa" : "data"}</Button></div></div>
    <Card><CardContent className="p-0"><div className="flex flex-col gap-3 border-b border-line p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:max-w-xs"><Search className="absolute left-3 top-2.5 text-muted" size={16} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari data..." className="h-9 w-full rounded-lg border border-line pl-9 pr-3 text-xs outline-none focus:border-brand" /></div><div className="flex items-center gap-2"><Button variant="ghost" size="sm"><Filter size={14} /> Filter</Button><Button variant="ghost" size="sm"><ArrowDownToLine size={14} /> Ekspor</Button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-canvas text-[10px] uppercase tracking-wider text-muted"><tr><th className="px-5 py-3.5">{section === "siswa" ? "Nama siswa" : "Nama"}</th><th className="px-5 py-3.5">{section === "jadwal" ? "Kelas" : section === "siswa" ? "Kelas" : "Detail"}</th><th className="px-5 py-3.5">Status / Jumlah</th><th className="px-5 py-3.5">Aktivitas</th><th className="px-5 py-3.5"></th></tr></thead><tbody className="divide-y divide-line">{filtered.map((r, i) => <tr key={r.secondary} className="group hover:bg-[#fcfcff]"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-brand-soft text-[11px] font-bold text-brand">{r.initials}</div><div><p className="font-bold text-ink">{r.primary}</p><p className="mt-1 text-[10px] text-muted">{r.secondary}</p></div></div></td><td className="px-5 py-4"><p className="font-semibold text-ink">{r.extra}</p></td><td className="px-5 py-4">{["sedang mengerjakan", "belum mulai", "selesai", "terputus", "berlangsung", "siap", "draft"].includes(r.badge) ? <StatusBadge status={r.badge} /> : <span className="font-bold text-ink">{r.badge}</span>}</td><td className="px-5 py-4 text-muted">{r.meta}</td><td className="px-5 py-4 text-right"><button onClick={() => notify(`Menu ${r.primary} dibuka`)} className="rounded-lg p-1.5 text-muted hover:bg-canvas hover:text-ink"><MoreHorizontal size={17} /></button></td></tr>)}</tbody></table></div>{filtered.length === 0 && <div className="p-10 text-center text-sm text-muted">Data tidak ditemukan.</div>}<div className="flex items-center justify-between border-t border-line px-5 py-3 text-[11px] text-muted"><span>Menampilkan {filtered.length} dari {rows.length} data</span><div className="flex gap-1"><button className="rounded border border-line px-2 py-1">‹</button><button className="rounded bg-brand px-2 py-1 font-bold text-white">1</button><button className="rounded border border-line px-2 py-1">›</button></div></div></CardContent></Card>
    {section === "jadwal" && <Card className="border-[#dddafe] bg-[#fbfbff]"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-brand-soft text-brand"><ShieldCheck size={19} /></div><div className="flex-1"><p className="text-sm font-bold text-ink">Semua jadwal aman dan tersinkronisasi</p><p className="mt-1 text-xs leading-5 text-muted">Realtime monitoring aktif. Perubahan status sesi akan muncul otomatis tanpa refresh.</p></div><Badge tone="brand"><span className="mr-1.5 h-1.5 w-1.5 animate-pulse rounded-full bg-brand" /> Supabase Realtime</Badge></CardContent></Card>}
    {showForm && <FormModal section={section} onClose={() => setShowForm(false)} onSave={() => { setShowForm(false); notify("Data berhasil disimpan"); }} />}{showImport && <ImportModal section={section} onClose={() => setShowImport(false)} onDone={() => { setShowImport(false); notify("File berhasil divalidasi"); }} />}{toast && <div className="fixed bottom-6 right-6 z-[60] flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-xs font-bold text-white shadow-xl"><Check size={15} className="text-[#71dfb5]" /> {toast}</div>}</div>;
}

function FormModal({ section, onClose, onSave }: { section: Section; onClose: () => void; onSave: () => void }) { const label = section === "siswa" ? "siswa" : section === "jadwal" ? "jadwal ujian" : section === "bank-soal" ? "bank soal" : section === "kelas" ? "kelas" : "mata pelajaran"; return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-line p-5"><div><h2 className="text-lg font-bold text-ink">Tambah {label}</h2><p className="mt-1 text-xs text-muted">Isi informasi berikut untuk menambahkan data baru.</p></div><button onClick={onClose} className="text-muted"><X size={19} /></button></div><div className="space-y-4 p-5"><Field label={section === "siswa" ? "Nama lengkap" : "Nama / judul"} placeholder={section === "siswa" ? "Contoh: Ahmad Fauzan" : "Masukkan nama"} />{section === "siswa" ? <><Field label="Kelas" placeholder="Pilih kelas" select /><div className="rounded-xl bg-brand-soft p-3 text-xs leading-5 text-[#5752a9]">No. Ujian dan password akan digenerate otomatis oleh sistem.</div></> : section === "jadwal" ? <><Field label="Kelas" placeholder="Pilih kelas" select /><Field label="Bank soal" placeholder="Pilih bank soal" select /><div className="grid grid-cols-2 gap-3"><Field label="Waktu mulai" placeholder="24/09/2024 08:00" /><Field label="Durasi (menit)" placeholder="120" /></div></> : <Field label="Keterangan" placeholder="Tambahkan keterangan (opsional)" />}</div><div className="flex justify-end gap-2 border-t border-line p-5"><Button variant="secondary" onClick={onClose}>Batal</Button><Button onClick={onSave}><Check size={15} /> Simpan data</Button></div></div></div>; }
function Field({ label, placeholder, select }: { label: string; placeholder: string; select?: boolean }) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-ink">{label}</span>{select ? <select className="h-10 w-full rounded-lg border border-line bg-white px-3 text-sm text-muted outline-none focus:border-brand"><option>{placeholder}</option><option>Pilih dari daftar</option></select> : <input placeholder={placeholder} className="h-10 w-full rounded-lg border border-line px-3 text-sm outline-none placeholder:text-[#b4bbc7] focus:border-brand" />}</label>; }
function ImportModal({ section, onClose, onDone }: { section: Section; onClose: () => void; onDone: () => void }) { const [file, setFile] = useState(false); const kind = section === "siswa" ? "siswa" : "soal"; return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-line p-5"><div><h2 className="text-lg font-bold text-ink">Impor {kind} dari Excel</h2><p className="mt-1 text-xs text-muted">Validasi dilakukan di browser sebelum data disimpan.</p></div><button onClick={onClose} className="text-muted"><X size={19} /></button></div><div className="space-y-4 p-5"><div className="rounded-xl border-2 border-dashed border-[#d8d5ff] bg-[#fbfbff] p-8 text-center"><FileSpreadsheet className="mx-auto text-brand" size={30} /><p className="mt-3 text-sm font-bold text-ink">{file ? "template-siswa.xlsx" : "Tarik file Excel ke sini"}</p><p className="mt-1 text-xs text-muted">atau pilih file dari perangkat · .xlsx / .xls</p><button onClick={() => setFile(true)} className="mt-4 text-xs font-bold text-brand">Pilih file</button></div><div className="flex items-start gap-2 rounded-xl bg-warning-soft p-3 text-xs leading-5 text-[#956b20]"><CircleHelp className="mt-0.5 shrink-0" size={15} /> Kolom wajib: <b>{section === "siswa" ? "Nama, Kelas" : "Nomor, Soal"}</b>. Duplikat dan data kosong akan ditandai sebelum commit.</div></div><div className="flex justify-between border-t border-line p-5"><button className="text-xs font-bold text-brand">Unduh template</button><div className="flex gap-2"><Button variant="secondary" onClick={onClose}>Batal</Button><Button disabled={!file} onClick={onDone}>Validasi file</Button></div></div></div></div>; }
